version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: simple_redis
    ports:
      - "6380:6379"
    volumes:
      - simple_redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    
  api:
    build: 
      context: ./api_service
      dockerfile: Dockerfile.simple
    container_name: simple_api
    ports:
      - "5001:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - API_KEY=test-api-key
      - FLASK_ENV=development
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

volumes:
  simple_redis_data: