version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - scraper_network
    
  api:
    build: 
      context: ./api_service
      dockerfile: Dockerfile.simple
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - API_KEY=demo-api-key-123
      - FLASK_ENV=production
      - LOG_LEVEL=INFO
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - scraper_network
    
  worker:
    build: 
      context: ./worker_service
      dockerfile: Dockerfile.simple
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - WORKER_TYPE=requests
      - MAX_WORKERS=3
      - POLL_INTERVAL=5
      - LOG_LEVEL=INFO
    depends_on:
      - redis
      - api
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - scraper_network

networks:
  scraper_network:
    driver: bridge

volumes:
  redis_data: