version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: scraper_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    
  api:
    build: ./api_service
    container_name: scraper_api
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - API_KEY=your-secret-api-key-here
      - FLASK_ENV=production
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    
  worker:
    build: ./worker_service
    container_name: scraper_worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - WORKER_TYPE=all
      - MAX_WORKERS=3
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
    deploy:
      replicas: 2

volumes:
  redis_data: