version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: test_redis
    ports:
      - "6380:6379"
    volumes:
      - test_redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    
  api:
    build: .
    container_name: test_api
    ports:
      - "5001:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - API_KEY=test-api-key
      - FLASK_ENV=development
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    
  test:
    build: .
    container_name: test_runner
    environment:
      - API_BASE_URL=http://api:5000
      - API_KEY=test-api-key
      - TEST_MODE=true
    depends_on:
      - api
      - redis
    volumes:
      - ./:/app
    command: ["python", "test_api.py"]

volumes:
  test_redis_data: